server:
  port: 7397

mybatis:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bugstack?useUnicode=true
    username: root
    password: 123456
    mapper-locations: classpath*:mapper/*.xml
    base-dao-package: cn.bugstack.middleware.test.infrastructure.dao
